### ISSUE TITLE
type = 'all' argument to get_prism_annual fails

### ISSUE THREAD

**Issue by vlahm** [ropensci/prism#100]
This produces a loading bar, but no output, and nothing is written to `prism.path`

```
> options(prism.path = paste0(getwd(), '/data/prism_raw'))
> get_prism_annual(type = 'all', year = 2010:2011, keepZip = TRUE)
```
This, however, works fine:
`get_prism_annual(type = 'ppt', year = 2010:2011, keepZip = TRUE)`

There's also some obsolete wording in the description section for this function:
'If the "all" parameter is set to TRUE, it will override any months entered and download all data.'

**Comment by rabutler-usbr** [comment]
Thank you for filing this! And I'm sorry for the delayed response. 

The next release which will be submitted to CRAN asap fixes this, but no longer allows for the "all" type to be passed into any of the `get_prism_*()` functions.

**Comment by vlahm** [comment]
No worries! Thanks for taking care of this.
