### ISSUE TITLE
dev version argument does not work for devtools 2.3.2

### ISSUE THREAD

**Issue by ARMurray** [ropensci/prism#101]
I would consider changing the dev install suggestion to: devtools::install_github('ropensci/prism') 

https://github.com/ropensci/prism/blob/master/README.md

user argument does not exist, but this code worked for me. Thank you for the prism_set_dl_dir function, it works great in loops!

**Comment by rabutler-usbr** [comment]
Great catch. We will update the README and new vignette. 

Absolutely. Glad you're finding it useful!
