### ISSUE TITLE
unavailable functions

### ISSUE THREAD

**Issue by kruehling** [ropensci/prism#102]
There are a number of functions within this package that seem to be unavailable and result in the error "could not find function .."  including but not limited to: pd_get_name(), mon_to_string(), prism_archive_subset() ? Other function appear to work fine. Any thoughts? 

Thanks !

**Comment by rabutler-usbr** [comment]
I am guessing that you have v0.1.0 installed from CRAN, while the README now shows functions included in v0.2.0? 

Can you install from GitHub (`devtools::install_github("ropensci/prism")`) to get all the v0.2.0 functionality?

**Comment by rabutler-usbr** [comment]
I am going to close this, but feel free to re-open if you still are having issues with v0.2.0
