### ISSUE TITLE
Normals download not working

### ISSUE THREAD

**Issue by MichaelTroutman** [ropensci/prism#106]
Hi, 

I have been having issues with the 30-yr normals download. Whenever I try to download the normals data it says I can't download it because it is already downloaded but does not appear in my archive or anywhere on my computer. I downloaded data directly from the prism website which worked, but I cannot download files through the r package. Below is an example of my code. Note that the normals data listed in the archive is what I downloaded manually. 

![snap](https://user-images.githubusercontent.com/54594789/146275753-3cc7247a-f306-4f50-841e-517133a1d0e3.PNG)

It only seems to affect the normals data since I can still import monthly data. Any idea why this is happening?

Michael

**Comment by rabutler-usbr** [comment]
@MichaelTroutman - it was an issue on the PRISM site that they fixed. It is now working for me, but please let me know if it no longer works for you.

**Comment by MichaelTroutman** [comment]
It works now. Thank you for looking into it!

**Comment by rabutler-usbr** [comment]
Always easy when it doesn't take any code changes :)
