### ISSUE TITLE
Add vignette dependencies as Suggests in DESCRIPTION

### ISSUE THREAD

**Issue by maelle** [ropensci/prism#107]
E.g. rgdal

See failure in https://github.com/r-universe/ropensci/runs/4511977387?check_suite_focus=true

```
Reading 'vignettes/prism_example.Rmd'
-- RMarkdown error -------------------------------------------------------------
Be sure to set the download folder using `prism_set_dl_dir()`.
Loading required package: sp
Quitting from lines 15-23 (prism_example.Rmd) 
Error in library(rgdal) : there is no package called 'rgdal'
--------------------------------------------------------------------------------
Error : Failed to render RMarkdown
```

**Comment by maelle** [comment]
@rabutler @rabutler-usbr friendly reminder :smile_cat:

**Comment by rabutler-usbr** [comment]
Thank you for the reminder @maelle. I'll take care of this by the end of the week.

**Comment by rabutler-usbr** [comment]
@maelle Are you getting prism from this repo or CRAN? And how do I make sure my fix worked; are there nightly build in that repo?

**Comment by maelle** [comment]
Thank you! Here's the dashboard with about hourly builds https://ropensci.r-universe.dev/ui#builds

**Comment by rabutler-usbr** [comment]
@maelle - I might need a little help. The builds on ropensci.r-universe are failing on windows b/c it's using terra v1.14-22, but v1.15.12 is required. 

It looks like the latest version of raster requires v1.15.12 of terrra. 

My builds (https://github.com/ropensci/prism/runs/5046531206?check_suite_focus=true) are getting v1.15.22 from CRAN, so not sure why v.1.14-22 is being used on ropensci.

**Comment by maelle** [comment]
I'll get back to you next week, thanks for your patience.

**Comment by rabutler-usbr** [comment]
Thanks for your patience!

**Comment by maelle** [comment]
All green, actually!
