### ISSUE TITLE
Download failure

### ISSUE THREAD

**Issue by SaimaNiamat** [ropensci/prism#110]
When I try to download multiple files using the code: 
> get_prism_monthlys(type = "tmean", year = 2005:2021, mon = 1:12 , keepZip = FALSE ) 

I am getting the following error message. 
```
in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [services.nacse.org] Connection timed out after 10011 milliseconds
```
Is there any way to resolve this issue?

**Comment by rabutler-usbr** [comment]
I've successfully called `get_prism_monthlys()` as you provided from multiple computers on multiple networks and cannot recreate it. 

Could you try again? Maybe you had no connection at that time?
