### ISSUE TITLE
Unable to download, possible error with prism_not_downloaded()

### ISSUE THREAD

**Issue by bglarkin** [ropensci/prism#112]
When I exectute:

`
prism_set_dl_dir("~/Desktop/prism_temp")
prism_set_dl_dir("~/Desktop/prism_temp")
get_prism_normals(type = "ppt", resolution = "4km", annual = TRUE, keepZip = FALSE)`

I get the message 

` already exists. Skipping downloading.`

But I have not yet downloaded any files. I see that the function `prism_not_downloaded()` controls this, but I can't see what to do about it.

**Comment by Liu22Yi** [comment]
I met the same problem.

**Comment by Liu22Yi** [comment]
Here is the code I run:

install.packages("prism")
library(prism)

prism_set_dl_dir("~/prism", create = TRUE)

get_prism_normals("tmean", "4km", annual = TRUE, keepZip = FALSE)

Here is what I get:

> library(prism)
Be sure to set the download folder using `prism_set_dl_dir()`.
> 
> prism_set_dl_dir("~/prism", create = TRUE)
creating ~/prism
> 
> get_prism_normals("tmean", "4km", annual = TRUE, keepZip = FALSE)
  |                                                              |   0%
 already exists. Skipping downloading.
  |==============================================================| 100%

**Comment by ClairePalandri** [comment]
I have the exact same problem with `get_prism_normals()`

**Comment by rabutler** [comment]
@ClairePalandri @bglarkin  @Liu22Yi - will you list what operating system and version of R you are using, please?

**Comment by rabutler** [comment]
@ClairePalandri  - the R package downloads the data directly from Oregon State, so you will get the same data. The documentation is out of date. You'll get 91-2020 normals.

**Comment by bglarkin** [comment]
@rabutler sure thing, thank you.
mac OS 13.2.1 (22D68)
R version 4.2.2 (2022-10-31)

Also thank you for confirming that direct downloads from Oregon State retrieve the same data.

**Comment by ClairePalandri** [comment]
> @ClairePalandri @bglarkin @Liu22Yi - will you list what operating system and version of R you are using, please?

I have had the same issue on two machines:
- one using mac OS 13.2.1 (22D68) and R version 4.2.1.
- the other Windows Server 2019 Standard, Version 1809, and R version 4.2.2

**Comment by rabutler-usbr** [comment]
@bglarkin @ClairePalandri  @Liu22Yi  - Thank you all for flagging this issue! 

I reached out to Oregon State and they fixed an issue with the API for normals. The R functions should be working again. 

Please re-open if they are not for you.

**Comment by bglarkin** [comment]
@rabutler-usbr all works as expected now. Thank you very much!
