### ISSUE TITLE
Delete prism files

### ISSUE THREAD

**Issue by emhart** [ropensci/prism#15]
Using `.Platform$OS` delete all the files by sending a system command.

**Comment by kendonB** [comment]
Is this better achieved by using ``file.remove()`` from base R?

**Comment by emhart** [comment]
Yeah, that thinking is definitely outdated. Although I'm not sure if this is an option we want anymore.  Do we want to enable deletion of files within R?

**Comment by kendonB** [comment]
Deletion of files will be needed when/if we get to updating files to their latest version. But this doesn't necessarily need it's own utility function. Users can always delete files if they want to, via any of the methods they know.
