### ISSUE TITLE
Bug with path

### ISSUE THREAD

**Issue by kendonB** [ropensci/prism#27]
I call:

    get_prism_dailys(type = "tmax", minDate = "2009-01-01",
                     maxDate = "2009-01-01", keepZip = TRUE)

and the prompt comes up:

    You have not set a path to hold your prism files
    Please enter the full path to download files to (hit enter to use default '~/prismtmp')

I put the directory I want, and I get the following error message:
    
    Error in list.files(options("prism.path")[[1]]) : invalid 'path' argument

I am on Windows 8.1 x64 running R x64 3.2.0

Hope this helps

**Comment by emhart** [comment]
Hi @kendonB I think I fixed the bug with this latest push, there was a bug in setting the option with this default.   However you can circumvent this default path setting problem by setting the path manually.  

`options(prism.path = "/my/path/prismtmp")`

I haven't used a windows machine in a long time so I'm not totally sure how best to set paths in R with Windows.  Let me know if this fix works though, with the default setting.
