### ISSUE TITLE
Output lat-long-weather data to .csv, .dta, and .RData formats

### ISSUE THREAD

**Issue by kendonB** [ropensci/prism#31]

**Comment by emhart** [comment]
The package is essentially done I think now, what did you have in mind for this feature?

**Comment by kendonB** [comment]
The behavior for this function would 

* Take a ``data.frame`` of lon-lat pairs
* Find the PRISM grid rows and columns associated with each lon-lat pair
* Return the weather data for a given set of dates as a data.frame.

I changed my mind and don't think it should be in the scope of this package to save ``data.frame``s to particular formats as this introduces extra dependencies. This is easily done at the user level once they have a ``data.frame``.
