### ISSUE TITLE
201404 tmin doesn't download

### ISSUE THREAD

**Issue by kendonB** [ropensci/prism#37]
Confirmed in the browser. Ted, can you try this on your machine so we can be sure it's not windows?

ftp://prism.nacse.org/monthly/tmin/2014/PRISM_tmin_stable_4kmM2_201404_bil.zip

**Comment by emhart** [comment]
I just downloaded it no problem from my browser, the package works too although I get a warning:

```R
> get_prism_monthlys("tmin",2014,4)
You have not set a path to hold your prism files.
Please enter the full path to download files to (hit enter to use default '~/prismtmp'): 

Warning message:
In normalizePath(user_path, winslash = "/") :
  path[1]="": No such file or directory

> ls_prism_data(name=T)
                               files                                     product_name
1 PRISM_tmin_stable_4kmM2_201404_bil Apr  2014 - 4km resolution - Minimum temperature
> 
```

**Comment by kendonB** [comment]
Can you confirm that you can open it in R? When downloading in the browser it get to about 95% and stopped each time.

**Comment by emhart** [comment]
Yup, I was able to download using the package and made a quick plot with `prism_image()`

**Comment by kendonB** [comment]
Confirmed this downloads and reads in on a linux terminal using wget just fine.

**Comment by kendonB** [comment]
OK it's fixed - had to add this as wrappers around each download function:

    if (Sys.info()["sysname"] == "Windows") {
      current_net2_status <- setInternet2(NA)
      setInternet2(FALSE)
    }
    {download_expr}
    if (Sys.info()["sysname"] == "Windows") {
      setInternet2(current_net2_status)
    }

I've also fixed up ``path_check()`` to deal with that warning message.
