### ISSUE TITLE
Add leaflet raster plots?

### ISSUE THREAD

**Issue by emhart** [ropensci/prism#39]
https://rstudio.github.io/leaflet/raster.html  

This is cool, but I'm not sure we want to add `LeafletJS` as a dependency.

**Comment by kendonB** [comment]
These look great! But probably outside the scope of what the package should do. We could potentially put it in ``Suggests`` and, in the plotting function, check if it's loaded.

**Comment by emhart** [comment]
Code for doing this is here:  https://gist.github.com/emhart/68888b7bcf1794f08cdf  Not that it should be added to the package
