### ISSUE TITLE
Travis isn't building - rgdal package not available

### ISSUE THREAD

**Issue by kendonB** [ropensci/prism#40]

**Comment by kendonB** [comment]
Trying adding rgdal to imports rather than suggests

**Comment by kendonB** [comment]
Can always just modify tests to use the ``raster`` package.

**Comment by emhart** [comment]
I don't think we actually need to import rgdal.

**Comment by kendonB** [comment]
I think Travis automatically runs the ``testthat`` scripts, which currently use ``rgdal`` to read in the files

**Comment by emhart** [comment]
I got lazy with the tests and just renamed the folder so it builds now.
