### ISSUE TITLE
Fix progress bars in daily and monthly

### ISSUE THREAD

**Issue by emhart** [ropensci/prism#47]
Looks like I mucked up the progress bars in my daily and monthly downloads, should be an easy fix.

**Comment by kendonB** [comment]
I just messed with these in my latest update. Could have been my fault. Can you post a replication?

**Comment by emhart** [comment]
The issue with this is that you can only set the length by years for data pre-1981 within the loop (in an easy way that is) so each chunk of the bar is 1 year, vs 1 month.  There could be a work around, but I'm not sure it's worth it.
