### ISSUE TITLE
1981 doesn't download with get_prism_monthlys

### ISSUE THREAD

**Issue by ylarissa** [ropensci/prism#59]
I think because of the way the code is written:
  pre_1981 <- years[years < 1981]
  post_1981 <- years[years > 1981]
if you choose years that span 1981 in get_prism_monthlys, 1981 itself doesn't download. Maybe if an "=" was added (post_1981 <- years[years >= 1981]), 1981 would get included.
Thanks!

**Comment by sdtaylor** [comment]
I just ran into this and I think @ylarissa would fix it as well. This is also an issue if you only want data from 1981, in which case it throws an error.

**Comment by rabutler** [comment]
#63 closes this
