### ISSUE TITLE
Push to CRAN?

### ISSUE THREAD

**Issue by kendonB** [ropensci/prism#62]
There is at least one documentation update and the check = "httr" option that aren't on the CRAN version.

@emhart

**Comment by rabutler** [comment]
@emhart @kendonB 

Let me know if you'd like any assistance. I'm happy to put in some time fixing errors on the current travis build.

**Comment by kendonB** [comment]
Extra help will be very appreciated! Thanks heaps for what you've been doing thus far

**Comment by rabutler** [comment]
@emhart Any plans to push up a CRAN release based on the last few PRs? Or if not, are there still some issues you'd like to resolve before the next CRAN release?

I'm happy to help with the work to push to CRAN if it's a time thing.

**Comment by emhart** [comment]
@rabutler I just need to write a change file based on your PR's and then we can submit it. Do you have something handy?

**Comment by rabutler** [comment]
@emhart I just went through the checks again and made a few updates so there are no notes in R CMD CHECK. See PR #72 

I think the only things left to do are change the version in News and Descriptions. (And consider adding me as a contributor :) )

**Comment by rabutler** [comment]
@emhart I forgot to mention- the tests are not actually being run because there is no testthat.R file in the tests folder. It would take a little bit to clean the existing tests up for testthat, but I could do that before the cran release if you'd like.

**Comment by emhart** [comment]
@cjcarlson Yeah, curse my small children!  (You could write a paper about the impact of babies on open source projects).  Anyway, the pre 1981 data was a bit of a hack because you have to download all of the data, and then just load the specific files you want.  I'm not sure when I'll have time to take the mantle back up.  Maybe @rabutler or @kendonB have some time to work on it.

**Comment by rabutler-usbr** [comment]
@emhart If you want to grant me write access to the repository, I'm happy to merge in #72 and then submit to CRAN. 

@cjcarlson does the current dev version on GitHub work for getting the pre 1981 data for you?

**Comment by emhart** [comment]
@rabutler-usbr Granted!

**Comment by rabutler-usbr** [comment]
Thanks @emhart!

I'll go ahead and merge in #72, and then update the version number. I'll suggest going to v0.1.0, unless you prefer it to got to v0.0.8?

Also, would you like me to add my email as the maintainer so I get the CRAN review emails, or do you prefer to stay listed as the maintainer?

**Comment by rabutler-usbr** [comment]
Just going through the final checks in `devtools::release()` now. Expect to submit later today.

**Comment by rabutler-usbr** [comment]
uploaded to CRAN

**Comment by rabutler-usbr** [comment]
v0.1.0 is now available on CRAN. 

@cjcarlson please file a separate issue if you still have problems with pre-1981 data.
