### ISSUE TITLE
get_prism_dailys() dates argument does not work

### ISSUE THREAD

**Issue by rabutler** [ropensci/prism#66]
When using the `dates` argument, `get_prism_dailys()` returns the following error:

> Error in format.default(dates, "%Y") : invalid 'trim' argument

It does not matter if you have only one or more than one value. 

The following works:
```
get_prism_dailys("ppt", minDate = "2015-09-01", maxDate = "2015-09-01", keepZip = FALSE)
get_prism_dailys("ppt", minDate = "2015-09-01", maxDate = "2015-09-02", keepZip = FALSE)
```

The following does not work:
```
prism::get_prism_dailys("ppt", dates = "2015-09-01", keepZip = FALSE)
prism::get_prism_dailys("ppt", dates = c("2015-09-01", "2015-09-02"), keepZip = FALSE)
```

**Comment by rabutler** [comment]
Looks like I might have misread the `dates` argument in the help file, or that the help file is a little unclear. If `dates` is already a Date, then it works, i.e., `get_prism_dailys("ppt", dates = as.Date("2015-09-01"), keepZip = FALSE)` works. 

However, since `minDate` and `maxDate` can be specified as characters, does it make sense to allow that for `dates` too? A quick `as.Date(dates)` in `gen_dates()` would allow this.

**Comment by emhart** [comment]
@rabutler good point, I can fix this, looks like there were a few bugs so a new submission to cran is in order.

**Comment by rabutler** [comment]
Thanks @emhart. I'm happy to submit a pr with that fix. Just didn't want to if it was not with the spirit of what was intended by that parameter.
