### ISSUE TITLE
extend functions to work with vpdmin and vpdmax

### ISSUE THREAD

**Issue by rabutler** [ropensci/prism#68]
Need all `get_*()` functions to also work for vapor pressure deficit

- [x] `get_prism_monthlys()`
- [x] `get_prism_annual()`
- [x] `get_prism_dailys()`
- [x] `get_prism_normals()`

**Comment by rabutler-usbr** [comment]
`get_prism_normals("vpdmin", "4km", annual = TRUE)` works
