### ISSUE TITLE
extend subset_prism_folders() to work for monthly and annual folders

### ISSUE THREAD

**Issue by rabutler** [ropensci/prism#69]
Right now `prism:::subset_prism_folders(type = "tmax", dates = "200001")` returns `character(0)` even if that folder does exist

**Comment by rabutler-usbr** [comment]
Can this also be exported so that users don't have to grep. Ex:

```
to_slice <- grep("tmin",ls_prism_data()[,1],value = TRUE)
```

Get's all the tmin files, but would be nice to just use `subset_prism_folders()` and tell it you want monthly tmin, for all months, or a subset of months.

**Comment by rabutler-usbr** [comment]
Need:

- [ ] `filter_folders()` daily tests
- [ ] `filter_folders()` normals tests
- [ ] `prism_subset_folders()` error tests
