### ISSUE TITLE
options(prism.path = "~/prismtmp") not creating in expected directory

### ISSUE THREAD

**Issue by jbreng** [ropensci/prism#76]
Set RStudio project working directory using setwd().  Also set "Default Working Directory" in global options in RStudio to the same directory used in setwd().  When using options(prism.path = "~/prismtmp") in RStudio and then get_prism_daily() function, the file directory is created in a directory that doesn't match the working directory.  I want to delete the files using unlink() at end of script but files never seem to download to a consistent directory.

**Comment by emhart** [comment]
@jbreng what path is created?

**Comment by jbreng** [comment]
options(prism.path = "~/prismtmp") function consistently creates a path in my "My Documents" folder, regardless of setwd() path or changing RStudio global options.  Path = "C:\Users\jbren\Documents".  Ultimately, it'd be very helpful to understand if file path directory is created in same spot all the time via the options() function.  especially since I want to delete the downloaded prism files.

**Comment by jbreng** [comment]
Using options(prism.path = "~/prismtmp") may not always write to "My Documents" folder.  After starting a new R project and file, it is now saving PRISM files to "C:" Drive.  Is there a way to pull the absolute path set using options(prism.path = "/prismtmp") so that it can be deleted?  Perhaps this is not an "issue", I just might not understand file directory access of relative paths...

**Comment by jbreng** [comment]
At this point, and I'm thinking it's related to consistent change in directory by using options(), the prism_stack and ls_prism_data functions crash.  "Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : Cannot create a RasterLayer object from this file. (file does not exist)"

**Comment by rabutler-usbr** [comment]
@jbreng 

I don't think this is an issue with the package. I'd suggest taking a look at `expand.path()` for how the `~` is expanded on Windows. `~` is not tied to the working directory. 

I'd also suggest specifically setting the prism path if the tilde expansion is an issue. If you set it to a relative path, then it should work with your working directory, and also with unlink.

**Comment by jbreng** [comment]
Ok. thanks for the suggestions.  path.expand() allowed me to see what "~" represented.  This R package is great!  Might I make a small suggestion?  As the read me is currently structured, a novice in R like myself, might find it difficult to understand how options() sets the file path and whether it is a relative or absolute path being created.  Ultimately, makes it difficult to know where files were downloaded.  Could further explanation be provided in the read.me?  Again, thanks for the help!

**Comment by rabutler-usbr** [comment]
@jbreng thanks for the suggestion. I think we'll take a look at the readme and also see if we can provide some message on load that helps you know for sure where the files will be downloaded at.
